const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Timeline,
		C3.Plugins.qrcode,
		C3.Plugins.sliderbar,
		C3.Plugins.Particles,
		C3.Behaviors.Bullet,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Sprite: 0},
	{DragDrop: 0},
	{gelas: 0},
	{jenis: 0},
	{teh: 0},
	{BtnStart: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{information: 0},
	{Tween: 0},
	{Text: 0},
	{BtnMusic: 0},
	{Audio: 0},
	{Sprite9: 0},
	{spr: 0},
	{infoPanel: 0},
	{InfoObject: 0},
	{TxtInfo: 0},
	{BtnCloseInfo: 0},
	{Text2: 0},
	{Sprite6: 0},
	{Continue: 0},
	{Text3: 0},
	{Text4: 0},
	{target: 0},
	{Monolog: 0},
	{Back: 0},
	{TEXTPENJELASAN: 0},
	{full_Text: 0},
	{Array: 0},
	{Next: 0},
	{Larutans: 0},
	{Ion: 0},
	{bgBlur: 0},
	{Sprite7: 0},
	{retry: 0},
	{board: 0},
	{Sprite8: 0},
	{Jeruk: 0},
	{Runner: 0},
	{sdad: 0},
	{Sprite2: 0},
	{Text5: 0},
	{text_gagal: 0},
	{Text6: 0},
	{text_evaluasi: 0},
	{Text7: 0},
	{teh_uji_coba: 0},
	{uji_coba: 0},
	{jeruk_uji_coba: 0},
	{air_ujicoba: 0},
	{Touch: 0},
	{bgg: 0},
	{vid2: 0},
	{Larutan_ekspresi: 0},
	{Jeruk_Ekspresi_1: 0},
	{Sprite5: 0},
	{nonelektro: 0},
	{TimelineController: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{QRCode: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{SliderBar: 0},
	{Particles: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Text8: 0},
	{air_gelas: 0},
	{ai_belakng: 0},
	{Bullet: 0},
	{particle_positive: 0},
	{Tilemap: 0},
	{Solid: 0},
	{solid: 0},
	{Sprite23: 0},
	{nonIon: 0},
	{JAWABAN: 0},
	{TEXTJAWABAN: 0},
	{tujuan: 0},
	{C: 0},
	{textJawabanna: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{QRCode2: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{InfoOn: 0},
	{MusicOn: 0},
	{progress: 0},
	{Ujicoba: 0},
	{Waiting: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	gelas: class extends self.ISpriteInstance {},
	teh: class extends self.ISpriteInstance {},
	BtnStart: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	information: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	spr: class extends self.ISpriteInstance {},
	infoPanel: class extends self.ISpriteInstance {},
	InfoObject: class extends self.ISpriteInstance {},
	TxtInfo: class extends self.ITextInstance {},
	BtnCloseInfo: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Continue: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	target: class extends self.ISpriteInstance {},
	Monolog: class extends self.ITextInstance {},
	Back: class extends self.ISpriteInstance {},
	TEXTPENJELASAN: class extends self.ITextInstance {},
	full_Text: class extends self.ITextInstance {},
	Array: class extends self.IArrayInstance {},
	Next: class extends self.ISpriteInstance {},
	Larutans: class extends self.ISpriteInstance {},
	Ion: class extends self.ISpriteInstance {},
	bgBlur: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	retry: class extends self.ISpriteInstance {},
	board: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Jeruk: class extends self.ISpriteInstance {},
	Runner: class extends self.ISpriteInstance {},
	sdad: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	text_gagal: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	text_evaluasi: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	teh_uji_coba: class extends self.ISpriteInstance {},
	uji_coba: class extends self.ISpriteInstance {},
	jeruk_uji_coba: class extends self.ISpriteInstance {},
	air_ujicoba: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	bgg: class extends self.ISpriteInstance {},
	vid2: class extends self.ISpriteInstance {},
	Larutan_ekspresi: class extends self.ISpriteInstance {},
	Jeruk_Ekspresi_1: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	nonelektro: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	QRCode: class extends self.IQRCodeInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Text8: class extends self.ITextInstance {},
	air_gelas: class extends self.ISpriteInstance {},
	ai_belakng: class extends self.ISpriteInstance {},
	particle_positive: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	solid: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	nonIon: class extends self.ISpriteInstance {},
	JAWABAN: class extends self.ITextInstance {},
	TEXTJAWABAN: class extends self.ITextInstance {},
	C: class extends self.ISpriteInstance {},
	textJawabanna: class extends self.ITextInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	QRCode2: class extends self.IQRCodeInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {}
}