const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.video,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Touch.Cnds.OnTouchObject
	];
};
self.C3_JsPropNameTable = [
	{Larutan: 0},
	{Mouse: 0},
	{Sprite: 0},
	{Video: 0},
	{Video2: 0},
	{Video3: 0},
	{DragDrop: 0},
	{gelas: 0},
	{jenis: 0},
	{teh: 0},
	{BtnStart: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{information: 0},
	{Tween: 0},
	{Text: 0},
	{BtnMusic: 0},
	{Sprite5: 0},
	{Audio: 0},
	{Sprite9: 0},
	{spr: 0},
	{infoPanel: 0},
	{InfoObject: 0},
	{TxtInfo: 0},
	{BtnCloseInfo: 0},
	{Text2: 0},
	{Sprite6: 0},
	{Continue: 0},
	{Text3: 0},
	{Text4: 0},
	{target: 0},
	{Monolog: 0},
	{Back: 0},
	{TEXTPENJELASAN: 0},
	{full_Text: 0},
	{Array: 0},
	{Next: 0},
	{Larutans: 0},
	{Ion: 0},
	{bgBlur: 0},
	{Sprite7: 0},
	{retry: 0},
	{board: 0},
	{Sprite8: 0},
	{Jeruk: 0},
	{Runner: 0},
	{Jeruk_Ekspresi: 0},
	{larutan_ekspresi: 0},
	{Teh_Ekspresi: 0},
	{Sprite2: 0},
	{Text5: 0},
	{text_gagal: 0},
	{Text6: 0},
	{text_evaluasi: 0},
	{Text7: 0},
	{teh_uji_coba: 0},
	{uji_coba: 0},
	{jeruk_uji_coba: 0},
	{air_ujicoba: 0},
	{vid: 0},
	{Touch: 0},
	{InfoOn: 0},
	{MusicOn: 0},
	{SectionIndex: 0},
	{Ujicoba: 0}
];

self.InstanceType = {
	Larutan: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Video2: class extends self.IWorldInstance {},
	Video3: class extends self.IWorldInstance {},
	gelas: class extends self.ISpriteInstance {},
	teh: class extends self.ISpriteInstance {},
	BtnStart: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	information: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	spr: class extends self.ISpriteInstance {},
	infoPanel: class extends self.ISpriteInstance {},
	InfoObject: class extends self.ISpriteInstance {},
	TxtInfo: class extends self.ITextInstance {},
	BtnCloseInfo: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Continue: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	target: class extends self.ISpriteInstance {},
	Monolog: class extends self.ITextInstance {},
	Back: class extends self.ISpriteInstance {},
	TEXTPENJELASAN: class extends self.ITextInstance {},
	full_Text: class extends self.ITextInstance {},
	Array: class extends self.IArrayInstance {},
	Next: class extends self.ISpriteInstance {},
	Larutans: class extends self.ISpriteInstance {},
	Ion: class extends self.ISpriteInstance {},
	bgBlur: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	retry: class extends self.ISpriteInstance {},
	board: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Jeruk: class extends self.ISpriteInstance {},
	Runner: class extends self.ISpriteInstance {},
	Jeruk_Ekspresi: class extends self.ISpriteInstance {},
	larutan_ekspresi: class extends self.ISpriteInstance {},
	Teh_Ekspresi: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	text_gagal: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	text_evaluasi: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	teh_uji_coba: class extends self.ISpriteInstance {},
	uji_coba: class extends self.ISpriteInstance {},
	jeruk_uji_coba: class extends self.ISpriteInstance {},
	air_ujicoba: class extends self.ISpriteInstance {},
	vid: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {}
}